"""empty message

Revision ID: 42d84c8a6b31
Revises: 
Create Date: 2022-03-10 01:05:33.755450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d84c8a6b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=256), nullable=True),
    sa.Column('campaign_name', sa.String(length=256), nullable=True),
    sa.Column('bid_startegy', sa.String(length=256), nullable=True),
    sa.Column('budget_remainin', sa.String(length=256), nullable=True),
    sa.Column('buying_type', sa.String(length=256), nullable=True),
    sa.Column('objective', sa.String(length=256), nullable=True),
    sa.Column('pacing_type', sa.String(length=256), nullable=True),
    sa.Column('smart_promotion_type', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.String(length=256), nullable=True),
    sa.Column('end_time', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Leadgens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.String(length=256), nullable=True),
    sa.Column('locale', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('leads_count', sa.Integer(), nullable=True),
    sa.Column('page_name', sa.String(length=256), nullable=True),
    sa.Column('created_time', sa.String(length=256), nullable=True),
    sa.Column('expired_leads_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Leadgens')
    op.drop_table('Campaign')
    # ### end Alembic commands ###
